### ISSUE TITLE
FEAT: User should be notified of an update pending on the My Content Page and have the ability to update the installed release

### ISSUE THREAD

**Issue by JonathanTurnock** [flying-dice/dcs-dropzone-mod-manager#15]
Given a user is on the my content page
When an update is present
Then they should be notified visually and can update accordingly

**Comment by john681611** [comment]
In the old pile of code, I wrote some functionality on the UI side to highlight apps that are out of date and do individual and mass updates. We may be able to recover that.

**Comment by JonathanTurnock** [comment]
@john681611 I'm going to get a naive impl of this working so we can move towards an alpha release

**Comment by JonathanTurnock** [comment]
Resolved by #22
