### ISSUE TITLE
FEAT: Uninstall script to remove both working dirs and remove all symlinks

### ISSUE THREAD

**Issue by JonathanTurnock** [flying-dice/dcs-dropzone-mod-manager#17]
Given no access to the SQLite db
When a user uninstalls the app
Then it should remove both content and settings and remove all symlinks

Note this should cover both happy and unhappy paths where the db can either be intact or corrupt. 

The idea is that it shouldn't matter on uninstall.

**Comment by john681611** [comment]
This is done right?

**Comment by JonathanTurnock** [comment]
No this would be the electron uninstaller so it removes everything if a user nukes the install without opening the app.

**Comment by JonathanTurnock** [comment]
Resolved in #51
